<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dagangan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

    }

    function selectAllDagangan(){
        return $this->db->query("SELECT * FROM DAGANGAN, PEDAGANG WHERE PEDAGANG.idPedagang = DAGANGAN.idPedagang AND PEDAGANG.statusVerifikasiPedagang = TRUE")->result_array();
    }

    function selectAllDaganganByKataKunci($kataKunci){
        return $this->db->query("SELECT * FROM DAGANGAN WHERE DAGANGAN.namaDagangan 
                                LIKE '%$kataKunci%' ORDER BY case when soundex(DAGANGAN.namaDagangan) = soundex('$kataKunci')
                                then '1' else soundex(DAGANGAN.namaDagangan) end")->result_array();
    }

    function selectDagangan($idDagangan){
        return $this->db->query("SELECT * FROM DAGANGAN WHERE DAGANGAN.idDagangan = '$idDagangan'")->row_array();
    }

    function updateStatusBerjualanDagangan($idDagangan){
        $result = $this->db->query("SELECT `statusBerjualan` FROM `DAGANGAN` WHERE `idDagangan` = '$idDagangan'")->row_array();
        $statusBerjualan = $result['statusBerjualan'];
        $statusBerjualan = !$statusBerjualan;
        $this->db->query("UPDATE `DAGANGAN` SET `statusBerjualan`='$statusBerjualan' WHERE `idDagangan` = '$idDagangan'");
    }

    function isValidDagangan($idDagangan){
        if($this->db->query("SELECT * FROM DAGANGAN WHERE DAGANGAN.idDagangan = '$idDagangan'")->num_rows()>0)
            return true;
        else
            return false;
    }

    function insertDagangan($idPedagang, $namaDagangan, $deskripsiDagangan, $fotoDagangan, $tipeDagangan){
        $idDagangan = uniqid();
        $this->db->query("INSERT INTO `PRODUK`  (`idDagangan`, `idPedagang`, `namaDagangan`, `deskripsiDagangan`, `tipeDagangan`, `fotoDagangan`, `statusBerjualan`) VALUES 
                        ('$idDagangan', '$idPedagang', '$namaDagangan', '$deskripsiDagangan', '$tipeDagangan', '$fotoDagangan', False)");
    }

    function updateLokasiDagangan($idDagangan, $latDagangan, $lngDagangan){
        $this->db->query("UPDATE `DAGANGAN` SET `latDagangan` = '$latDagangan', `lngDagangan` = '$lngDagangan' WHERE `idDagangan` = '$idDagangan'");
    }
}
