<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dagangan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dagangan by ID_DAGANGAN
     */
    function get_dagangan_by_id_dagangan($ID_DAGANGAN)
    {
        return $this->db->get_where('DAGANGAN',array('ID_DAGANGAN'=>$ID_DAGANGAN))->result_array();
    }

    /*
     * Get dagangan by input
     */
    function get_dagangan_by_input($input)
    {
        return $this->db->query("SELECT * FROM dagangan WHERE MATCH (NAMA_DAGANGAN,DESKRIPSI_DAGANGAN) 
        AGAINST ('$input' IN NATURAL LANGUAGE MODE)")->result_array();
    }
    
    /*
     * Get all dagangan
     */
    function get_all_dagangan()
    {
        return $this->db->get('DAGANGAN')->result_array();
    }
    
    /*
     * function to add new dagangan
     */
    function add_dagangan($params)
    {
        $this->db->insert('DAGANGAN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dagangan
     */
    function update_dagangan($ID_DAGANGAN,$params)
    {
        $this->db->where('ID_DAGANGAN',$ID_DAGANGAN);
        $response = $this->db->update('DAGANGAN',$params);
        if($response)
        {
            return "dagangan updated successfully";
        }
        else
        {
            return "Error occuring while updating dagangan";
        }
    }
    
    /*
     * function to delete dagangan
     */
    function delete_dagangan($ID_DAGANGAN)
    {
        $response = $this->db->delete('DAGANGAN',array('ID_DAGANGAN'=>$ID_DAGANGAN));
        if($response)
        {
            return "dagangan deleted successfully";
        }
        else
        {
            return "Error occuring while deleting dagangan";
        }
    }
}
