<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Notifikasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function selectAllNotifikasi(){
        return $this->db->query("SELECT * FROM NOTIFIKASI,PEMBELI WHERE NOTIFIKASI.statusNotifikasi = TRUE AND NOTIFIKASI.idPembeli = PEMBELI.idPembeli")->result_array();
    }
    function updateNotifikasi($idPembeli, $idDagangan, $jarakNotifikasi, $statusNotifikasi){
        $this->db->query("UPDATE `NOTIFIKASI` SET `jarakNotifikasi`='$jarakNotifikasi', `statusNotifikasi`='$statusNotifikasi' WHERE `idPembeli` = '$idPembeli' AND `idDagangan` = '$idDagangan'");
    }

    function selectNotifikasiPembeli($idPembeli){
        return $this->db->query("SELECT NOTIFIKASI.idDagangan, DAGANGAN.latDagangan,DAGANGAN.lngDagangan, 
                                NOTIFIKASI.jarakNotifikasi FROM
                                `NOTIFIKASI`, `DAGANGAN` WHERE NOTIFIKASI.idDagangan = DAGANGAN.idDagangan
                                AND NOTIFIKASI.idPembeli ='$idPembeli' ")->result_array();


    }

    function isNotifikasi($idPembeli, $idDagangan){
        if($this->db->query("SELECT * FROM NOTIFIKASI WHERE NOTIFIKASI.idDagangan = '$idDagangan' AND 
                            NOTIFIKASI.idPembeli = '$idPembeli' AND NOTIFIKASI.statusNotifikasi = TRUE ")->num_rows()>0)
            return true;
        else
            return false;

    }

    function addNotifikasi($idPembeli, $idDagangan){
        $idNotifikasi = uniqid();
        $this->db->query("INSERT INTO `NOTIFIKASI`(`idNotifikasi`, `idPembeli`, `idDagangan`, `statusNotifikasi`, `jarakNotifikasi`) 
                          VALUES ('$idNotifikasi','$idPembeli','$idDagangan',FALSE ,0)");
    }

    function deleteNotifikasi($idPembeli, $idDagangan){
        $this->db->query("DELETE FROM `NOTIFIKASI` WHERE idPembeli = '$idPembeli' AND idDagangan = '$idDagangan'");
    }
}
