<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Notifikasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function updateNotifikasi($idNotifikasi, $jarakNotifikasi, $statusNotifikasi){
        $this->db->query("UPDATE `NOTIFIKASI` SET `jarakNotifikasi`='$jarakNotifikasi', `statusNotifikasi`='$statusNotifikasi' WHERE `idNotifikasi` = '$idNotifikasi'");
    }

    function selectNotifikasiPembeli($idPembeli){
        return $this->db->query("SELECT * FROM `NOTIFIKASI` WHERE `idPembeli`='$idPembeli'")->result_array();
    }
}
