<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Notifikasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notifikasi by ID_NOTIFIKASI
     */
    function get_notifikasi($ID_NOTIFIKASI)
    {
        return $this->db->get_where('NOTIFIKASI',array('ID_NOTIFIKASI'=>$ID_NOTIFIKASI))->row_array();
    }
    
    /*
     * Get all notifikasi
     */
    function get_all_notifikasi()
    {
        return $this->db->get('NOTIFIKASI')->result_array();
    }
    
    /*
     * function to add new notifikasi
     */
    function add_notifikasi($params)
    {
        $this->db->insert('NOTIFIKASI',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notifikasi
     */
    function update_notifikasi($ID_NOTIFIKASI,$params)
    {
        $this->db->where('ID_NOTIFIKASI',$ID_NOTIFIKASI);
        $response = $this->db->update('NOTIFIKASI',$params);
        if($response)
        {
            return "notifikasi updated successfully";
        }
        else
        {
            return "Error occuring while updating notifikasi";
        }
    }
    
    /*
     * function to delete notifikasi
     */
    function delete_notifikasi($ID_NOTIFIKASI)
    {
        $response = $this->db->delete('NOTIFIKASI',array('ID_NOTIFIKASI'=>$ID_NOTIFIKASI));
        if($response)
        {
            return "notifikasi deleted successfully";
        }
        else
        {
            return "Error occuring while deleting notifikasi";
        }
    }
}
