<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Obrolan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function insertObrolan($idDagangan, $idPembeli, $text, $sender){
        $idObrolan = uniqid();
        if ($sender = $idDagangan){
            $this->db->query("INSERT INTO `OBROLAN`(`idObrolan`, `idDaganganPengirim`, `idPembeliPenerima`, `text`, `waktuPengiriman`, `statusMelihat`) VALUES 
                              ('$idObrolan', '$idDagangan', '$idPembeli', '$text', now(), False)");
        }else{
            $this->db->query("INSERT INTO `OBROLAN`(`idObrolan`, `idDaganganPenerima`, `idPembeliPengirim`, `text`, `waktuPengiriman`, `statusMelihat`) VALUES 
                              ('$idObrolan', '$idDagangan', '$idPembeli', '$text', now(), False)");
        }
    }
}
