<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Obrolan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get obrolan by ID_OBROLAN
     */
    function get_obrolan($ID_OBROLAN)
    {
        return $this->db->get_where('OBROLAN',array('ID_OBROLAN'=>$ID_OBROLAN))->row_array();
    }
    
    /*
     * Get all obrolan
     */
    function get_all_obrolan()
    {
        return $this->db->get('OBROLAN')->result_array();
    }
    
    /*
     * function to add new obrolan
     */
    function add_obrolan($params)
    {
        $this->db->insert('OBROLAN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update obrolan
     */
    function update_obrolan($ID_OBROLAN,$params)
    {
        $this->db->where('ID_OBROLAN',$ID_OBROLAN);
        $response = $this->db->update('OBROLAN',$params);
        if($response)
        {
            return "obrolan updated successfully";
        }
        else
        {
            return "Error occuring while updating obrolan";
        }
    }
    
    /*
     * function to delete obrolan
     */
    function delete_obrolan($ID_OBROLAN)
    {
        $response = $this->db->delete('OBROLAN',array('ID_OBROLAN'=>$ID_OBROLAN));
        if($response)
        {
            return "obrolan deleted successfully";
        }
        else
        {
            return "Error occuring while deleting obrolan";
        }
    }
}
