<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pedagang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function selectAllPedagangByKataKunci($kataKunci){
        return $this->db->query("SELECT * FROM PEDAGANG, DAGANGAN WHERE DAGANGAN.idPedagang = PEDAGANG.idPedagang 
                                AND PEDAGANG.namaPedagang LIKE '%$kataKunci%' ORDER BY case when 
                                soundex(PEDAGANG.namaPedagang) = soundex('$kataKunci') then '1' else 
                                soundex(PEDAGANG.namaPedagang) end")->result_array();
    }

    function selectPedagang($idPedagang){
        return $this->db->query("SELECT * FROM PEDAGANG WHERE PEDAGANG.idPedagang = '$idPedagang'")->row_array();
    }

    function updateNamaPedagang($idPedagang, $namaPedagang){
        $this->db->query("UPDATE `PEDAGANG` SET `namaPedagang`='$namaPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function updateEmailPedagang($idPedagang, $emailPedagang){
        $this->db->query("UPDATE `PEDAGANG` SET `emailPedagang`='$emailPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function updatePasswordPedagang($idPedagang, $passwordPedagang){
        $this->db->query("UPDATE `PEDAGANG` SET `passwordPedagang`='$passwordPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function updateAlamatPedagang($idPedagang, $alamatPedagang){
        $this->db->query("UPDATE `PEDAGANG` SET `alamatPedagang`='$alamatPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function updateNoPonselPedagang($idPedagang, $noPonselPedagang){
        $this->db->query("UPDATE `PEDAGANG` SET `noPonselPedagang`='$noPonselPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function updateFotoPedagang($idPedagang, $fotoPedagang){
        $this->db->query("UPDATE `PEDAGANG` SET `fotoPedagang`='$fotoPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function updateStatusVerifikasiPedagang($idPedagang){
        $result = $this->db->query("SELECT `statusVerifikasiPedagang` FROM `PEDAGANG` WHERE `idPedagang` = $idPedagang")->row_array();
        $statusVerifikasiPedagang = $result['statusVerifikasiPedagang'];
        $statusVerifikasiPedagang = !$statusVerifikasiPedagang;
        $this->db->query("UPDATE `PEDAGANG` SET `statusVerifikasiPedagang`='$statusVerifikasiPedagang' WHERE `idPedagang` = '$idPedagang'");
    }

    function insertPedagang($noPonselPedagang, $passwordPedagang){
        $idPedagang = uniqid();
        $this->db->query("INSERT INTO `PEDAGANG`(`idPedagang`, `noPonselPedagang`, `passwordPedagang`, `statusVerifikasiPedagang`) VALUES
                        ('$idPedagang','$noPonselPedagang','$passwordPedagang',False)");
    }

    function isValidPasswordPedagang($idPedagang, $passwordPedagang){
        if($this->db->query("SELECT * FROM `PEDAGANG` WHERE `idPedagang` = '$idPedagang' AND `passwordPedagang` = '$passwordPedagang'")->num_rows() > 0)
            return true;
        else return false;
    }
}
