<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pelanggan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function countPelanggan($idDagangan){
        return $this->db->query("SELECT * FROM PELANGGAN WHERE PELANGGAN.idDagangan = '$idDagangan'")->num_rows();
    }

    function isBerlangganan($idDagangan, $idPembeli){
        if($this->db->query("SELECT * FROM PELANGGAN WHERE PELANGGAN.idDagangan = '$idDagangan' AND 
                            PELANGGAN.idPembeli = '$idPembeli'")->num_rows()>0)
            return true;
        else
            return false;

    }
}
