<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pengunjung_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengunjung by ID_PENGUNJUNG
     */
    function get_pengunjung($ID_PENGUNJUNG)
    {
        return $this->db->get_where('PENGUNJUNG',array('ID_PENGUNJUNG'=>$ID_PENGUNJUNG))->row_array();
    }
    
    /*
     * Get all pengunjung
     */
    function get_all_pengunjung()
    {
        return $this->db->get('PENGUNJUNG')->result_array();
    }
    
    /*
     * function to add new pengunjung
     */
    function add_pengunjung($params)
    {
        $this->db->insert('PENGUNJUNG',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengunjung
     */
    function update_pengunjung($ID_PENGUNJUNG,$params)
    {
        $this->db->where('ID_PENGUNJUNG',$ID_PENGUNJUNG);
        $response = $this->db->update('PENGUNJUNG',$params);
        if($response)
        {
            return "pengunjung updated successfully";
        }
        else
        {
            return "Error occuring while updating pengunjung";
        }
    }
    
    /*
     * function to delete pengunjung
     */
    function delete_pengunjung($ID_PENGUNJUNG)
    {
        $response = $this->db->delete('PENGUNJUNG',array('ID_PENGUNJUNG'=>$ID_PENGUNJUNG));
        if($response)
        {
            return "pengunjung deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pengunjung";
        }
    }
}
