<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Penilaian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function countPenilaian($idDagangan){
        return $this->db->query("SELECT * FROM PENILAIAN, PRODUK, DAGANGAN 
                                WHERE PENILAIAN.idProduk = PRODUK.idProduk AND 
                                PRODUK.idDagangan = DAGANGAN.idDagangan AND 
                                DAGANGAN.idDagangan = '$idDagangan'")->num_rows();
    }

    function selectPenilaian($idDagangan){
        return $this->db->query("SELECT * FROM PENILAIAN, PRODUK, DAGANGAN 
                                WHERE PENILAIAN.idProduk = PRODUK.idProduk AND 
                                PRODUK.idDagangan = DAGANGAN.idDagangan AND 
                                DAGANGAN.idDagangan = '$idDagangan'")->result_array();
    }

    function selectPenilaianProduk($idProduk){
        return $this->db->query("SELECT * FROM PENILAIAN WHERE PENILAIAN.idProduk = '$idProduk'")->result_array();
    }

    function countPenilaianProduk($idProduk){
        return $this->db->query("SELECT * FROM PENILAIAN WHERE PENILAIAN.idProduk = '$idProduk'")->num_rows();
    }

    function insertPenilaian($idPembeli, $idProduk, $nilaiPenilaian, $deskripsiPenilaian){
        $idPenilaian = uniqid();

        $this->db->query("INSERT INTO `PENILAIAN`  (`idPenilaian`, `idPembeli`, `idProduk`, `nilaiPenilaian`, `deskripsiPenilaian`) VALUES 
                        ('$idPenilaian', '$idPembeli', '$idProduk', '$nilaiPenilaian', '$deskripsiPenilaian')");
    }
}
