<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Penilaian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_penilaian($params)
    {
        return $this->db->get_where('PENILAIAN',$params);
    }

    /*
     * Get penilaian by ID_PENILAIAN
     */
    function get_penilaian_by_id_penilaian($ID_PENILAIAN)
    {
        return $this->db->get_where('PENILAIAN',array('ID_PENILAIAN'=>$ID_PENILAIAN))->result_array();
    }

    /*
     * Get count penilaian by ID_PENILAIAN
     */
    function get_count_penilaian($ID_PRODUK)
    {
        return $this->db->get_where('PENILAIAN',array('ID_PRODUK'=>$ID_PRODUK))->num_rows();
    }

    /*
     * Get penilaian by ID_PRODUK
     */
    function get_penilaian_by_id_produk($ID_PRODUK)
    {
        return $this->db->get_where('PENILAIAN',array('ID_PRODUK'=>$ID_PRODUK))->result_array();
    }

    /*
     * Get all penilaian
     */
    function get_all_penilaian()
    {
        return $this->db->get('PENILAIAN')->result_array();
    }
    
    /*
     * function to add new penilaian
     */
    function add_penilaian($params)
    {
        $this->db->insert('PENILAIAN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update penilaian
     */
    function update_penilaian($ID_PENILAIAN,$params)
    {
        $this->db->where('ID_PENILAIAN',$ID_PENILAIAN);
        $response = $this->db->update('PENILAIAN',$params);
        if($response)
        {
            return "penilaian updated successfully";
        }
        else
        {
            return "Error occuring while updating penilaian";
        }
    }
    
    /*
     * function to delete penilaian
     */
    function delete_penilaian($ID_PENILAIAN)
    {
        $response = $this->db->delete('PENILAIAN',array('ID_PENILAIAN'=>$ID_PENILAIAN));
        if($response)
        {
            return "penilaian deleted successfully";
        }
        else
        {
            return "Error occuring while deleting penilaian";
        }
    }
}
