<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Produk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function selectAllProdukByKataKunci($kataKunci){
        return $this->db->query("SELECT * FROM PRODUK, DAGANGAN WHERE DAGANGAN.idDagangan = PRODUK.idDagangan 
                                AND PRODUK.namaProduk LIKE '%$kataKunci%' ORDER BY case when 
                                soundex(PRODUK.namaProduk) = soundex('$kataKunci') then '1' else 
                                soundex(PRODUK.namaProduk) end")->result_array();
    }

    function selectProdukDagangan($idDagangan){
        return $this->db->query("SELECT * FROM PRODUK WHERE PRODUK.idDagangan = '$idDagangan'")->result_array();
    }

    function updateProduk($idProduk, $namaProduk, $deskripsiProduk, $hargaProduk, $satuanProduk, $fotoProduk){
        $this->db->query("UPDATE `PRODUK` SET `namaProduk`='$namaProduk', `deskripsiProduk`='$deskripsiProduk', `hargaProduk`='$hargaProduk', `satuanProduk`='$satuanProduk',`fotoProduk`='$fotoProduk' WHERE `idProduk` = '$idProduk'");
    }

    function insertProduk($idDagangan, $namaProduk, $deskripsiProduk, $fotoProduk, $hargaProduk, $satuanProduk){
        $idProduk = uniqid();
        $this->db->query("INSERT INTO `PRODUK`  (`idProduk`, `idDagangan`, `namaProduk`, `deskripsiProduk`, `fotoProduk`, `hargaProduk`, `satuanProduk`) VALUES 
                        ('$idProduk', '$idDagangan', '$namaProduk', '$deskripsiProduk', '$fotoProduk', '$hargaProduk', '$satuanProduk')");
    }

    function deleteProduk($idProduk){
        $this->db->query("DELETE FROM `PRODUK` WHERE `idProduk` = '$idProduk'");
    }
}
