<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Produk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get produk by ID_PRODUK
     */
    function get_produk_by_id_produk($ID_PRODUK)
    {
        return $this->db->get_where('PRODUK',array('ID_PRODUK'=>$ID_PRODUK))->result_array();
    }

    /*
     * Get produk by ID_PRODUK
     */
    function get_produk_by_id_dagangan($ID_DAGANGAN)
    {
        return $this->db->get_where('PRODUK',array('ID_DAGANGAN'=>$ID_DAGANGAN))->result_array();
    }

    /*
     * Get produk by input
     */
    function get_produk_by_input($input)
    {
        return $this->db->query("SELECT * FROM PRODUK WHERE MATCH (NAMA_PRODUK)
        AGAINST ('$input' IN BOOLEAN MODE)")->result_array();
    }

    /*
     * Get all produk
     */
    function get_all_produk()
    {
        return $this->db->get('PRODUK')->result_array();
    }
    
    /*
     * function to add new produk
     */
    function add_produk($params)
    {
        $this->db->insert('PRODUK',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update produk
     */
    function update_produk($ID_PRODUK,$params)
    {
        $this->db->where('ID_PRODUK',$ID_PRODUK);
        $response = $this->db->update('PRODUK',$params);
        if($response)
        {
            return "produk updated successfully";
        }
        else
        {
            return "Error occuring while updating produk";
        }
    }
    
    /*
     * function to delete produk
     */
    function delete_produk($ID_PRODUK)
    {
        $response = $this->db->delete('PRODUK',array('ID_PRODUK'=>$ID_PRODUK));
        if($response)
        {
            return "produk deleted successfully";
        }
        else
        {
            return "Error occuring while deleting produk";
        }
    }
}
